version: '3'
services:
  web:
    image: jeffmaher/django-dev
    ports:
      - '8000:8000'
    volumes: 
      - .:/workspace
    links:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust